2021-03-04T15:45:11: PM2 log: ===============================================================================
2021-03-04T15:45:11: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
2021-03-04T15:45:11: PM2 log: Time                 : Thu Mar 04 2021 15:45:11 GMT-0300 (Brasilia Standard Time)
2021-03-04T15:45:11: PM2 log: PM2 version          : 4.5.5
2021-03-04T15:45:11: PM2 log: Node.js version      : 14.15.4
2021-03-04T15:45:11: PM2 log: Current arch         : arm64
2021-03-04T15:45:11: PM2 log: PM2 home             : /data/data/com.termux/files/home/.pm2
2021-03-04T15:45:11: PM2 log: PM2 PID file         : /data/data/com.termux/files/home/.pm2/pm2.pid
2021-03-04T15:45:11: PM2 log: RPC socket file      : /data/data/com.termux/files/home/.pm2/rpc.sock
2021-03-04T15:45:11: PM2 log: BUS socket file      : /data/data/com.termux/files/home/.pm2/pub.sock
2021-03-04T15:45:11: PM2 log: Application log path : /data/data/com.termux/files/home/.pm2/logs
2021-03-04T15:45:11: PM2 log: Worker Interval      : 30000
2021-03-04T15:45:11: PM2 log: Process dump file    : /data/data/com.termux/files/home/.pm2/dump.pm2
2021-03-04T15:45:11: PM2 log: Concurrent actions   : 2
2021-03-04T15:45:11: PM2 log: SIGTERM timeout      : 1600
2021-03-04T15:45:11: PM2 log: ===============================================================================
2021-03-04T15:45:11: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:11: PM2 log: App [index:0] online
2021-03-04T15:45:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:45:11: PM2 error: Error while getting CLK_TCK Error: Command failed: getconf CLK_TCK
/data/data/com.termux/files/usr/bin/sh: 1: getconf: not found

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:529:15)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:529:15)
    at Pipe.<anonymous> (net.js:673:12)
    at Pipe.callbackTrampoline (internal/async_hooks.js:131:14) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'getconf CLK_TCK'
}
2021-03-04T15:45:11: PM2 error: Error while getting PAGESIZE Error: Command failed: getconf PAGESIZE
/data/data/com.termux/files/usr/bin/sh: 1: getconf: not found

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:529:15)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:529:15)
    at Pipe.<anonymous> (net.js:673:12)
    at Pipe.callbackTrampoline (internal/async_hooks.js:131:14) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'getconf PAGESIZE'
}
2021-03-04T15:45:13: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:13: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:13: PM2 log: App [index:0] online
2021-03-04T15:45:14: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:14: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:14: PM2 log: App [index:0] online
2021-03-04T15:45:16: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:16: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:16: PM2 log: App [index:0] online
2021-03-04T15:45:17: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:17: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:17: PM2 log: App [index:0] online
2021-03-04T15:45:19: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:19: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:19: PM2 log: App [index:0] online
2021-03-04T15:45:21: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:21: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:21: PM2 log: App [index:0] online
2021-03-04T15:45:22: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:22: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:22: PM2 log: App [index:0] online
2021-03-04T15:45:23: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:23: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:23: PM2 log: App [index:0] online
2021-03-04T15:45:25: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:25: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:25: PM2 log: App [index:0] online
2021-03-04T15:45:26: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:26: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:26: PM2 log: App [index:0] online
2021-03-04T15:45:28: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:28: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:28: PM2 log: App [index:0] online
2021-03-04T15:45:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:45:30: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:30: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:30: PM2 log: App [index:0] online
2021-03-04T15:45:32: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:32: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:32: PM2 log: App [index:0] online
2021-03-04T15:45:34: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:34: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:34: PM2 log: App [index:0] online
2021-03-04T15:45:37: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:37: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:37: PM2 log: App [index:0] online
2021-03-04T15:45:40: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:40: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:40: PM2 log: App [index:0] online
2021-03-04T15:45:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:45:43: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:43: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:43: PM2 log: App [index:0] online
2021-03-04T15:45:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:45:44: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:45:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:45:46: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:46: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:46: PM2 log: App [index:0] online
2021-03-04T15:45:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:45:48: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:45:49: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:45:49: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:49: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:49: PM2 log: App [index:0] online
2021-03-04T15:45:50: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:45:51: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:45:52: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:52: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:52: PM2 log: App [index:0] online
2021-03-04T15:45:52: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:45:54: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:45:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:45:56: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:56: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:56: PM2 log: App [index:0] online
2021-03-04T15:45:56: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:45:57: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:45:58: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:45:58: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:45:58: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:45:58: PM2 log: App [index:0] online
2021-03-04T15:45:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:46:01: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:01: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:01: PM2 log: App [index:0] online
2021-03-04T15:46:03: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:03: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:03: PM2 log: App [index:0] online
2021-03-04T15:46:05: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:05: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:05: PM2 log: App [index:0] online
2021-03-04T15:46:07: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:07: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:07: PM2 log: App [index:0] online
2021-03-04T15:46:09: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:09: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:09: PM2 log: App [index:0] online
2021-03-04T15:46:11: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:11: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:11: PM2 log: App [index:0] online
2021-03-04T15:46:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:46:13: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:13: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:13: PM2 log: App [index:0] online
2021-03-04T15:46:15: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:15: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:15: PM2 log: App [index:0] online
2021-03-04T15:46:17: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:17: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:17: PM2 log: App [index:0] online
2021-03-04T15:46:18: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:18: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:18: PM2 log: App [index:0] online
2021-03-04T15:46:20: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:20: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:20: PM2 log: App [index:0] online
2021-03-04T15:46:22: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:22: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:22: PM2 log: App [index:0] online
2021-03-04T15:46:24: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:24: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:24: PM2 log: App [index:0] online
2021-03-04T15:46:25: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:25: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:25: PM2 log: App [index:0] online
2021-03-04T15:46:27: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:27: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:27: PM2 log: App [index:0] online
2021-03-04T15:46:29: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:29: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:29: PM2 log: App [index:0] online
2021-03-04T15:46:31: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:31: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:31: PM2 log: App [index:0] online
2021-03-04T15:46:33: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:33: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:33: PM2 log: App [index:0] online
2021-03-04T15:46:35: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:35: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:35: PM2 log: App [index:0] online
2021-03-04T15:46:37: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:37: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:37: PM2 log: App [index:0] online
2021-03-04T15:46:39: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:39: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:39: PM2 log: App [index:0] online
2021-03-04T15:46:41: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:41: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:41: PM2 log: App [index:0] online
2021-03-04T15:46:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-03-04T15:46:43: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:43: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:43: PM2 log: App [index:0] online
2021-03-04T15:46:44: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:44: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:44: PM2 log: App [index:0] online
2021-03-04T15:46:46: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:46: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:46: PM2 log: App [index:0] online
2021-03-04T15:46:49: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:49: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:49: PM2 log: App [index:0] online
2021-03-04T15:46:52: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:52: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:52: PM2 log: App [index:0] online
2021-03-04T15:46:54: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:54: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:54: PM2 log: App [index:0] online
2021-03-04T15:46:56: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2021-03-04T15:46:56: PM2 log: App [index:0] starting in -fork mode-
2021-03-04T15:46:56: PM2 log: App [index:0] online
